### ISSUE TITLE
Implement calling built-in Functions

### ISSUE THREAD

**Issue by stasm** [projectfluent/fluent-rs#19]
`CallExpressions` currently don't implement the `ResolveValue` trait. In the first iteration let's add a simple `NUMBER()` built-in which doesn't even take any additional arguments.

@zbraniecki What are our options for locale-aware number- and date-formatting?

**Comment by zbraniecki** [comment]
There are none. I have the `fluent-locale` crate almost ready which will add language negotiation and we can mock a simple PluralRules on it. I wanted to use it as the first builtin.

As for number/date formatting, I don't believe there's anything yet in Rust, but I expect things to start popping up soon. For now, we could just add a custom NUMBER function that transliterates to eastern arabic numerals if the language is `ar`.

**Comment by zbraniecki** [comment]
@stasm - I think this is already fixed - you can add custom functions and they can be called. We still await a decent implementation of either `NUMBER` or `DATETIME` to provide built-ins.

Do you want to keep this issue open until we find and implement those two?

**Comment by zbraniecki** [comment]
closing as per lack of activity. reopen if needed.

**Comment by Xiretza** [comment]
I think this should be reopened, the built-in functions are still not implemented, which is either a bug in `fluent-rs` or in https://projectfluent.org/fluent/guide/functions.html.

**Comment by alerque** [comment]
@Xiretza This issue has a lot of unrelated discussion about the implementation needed to have functions in the first place. I suggest opening a new issue (or issues) for the specific function(s) that need to be implemented to be a full spec implementation. That will make it easier to track. Thanks.
